name: Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "Version of package"
        required: false
        default: "v1"
        type: string

jobs:
  manual-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "We run manual test!"
          echo "Selected environment: ${{github.event.inputs.environment}}"
          echo "Version: ${{github.event.inputs.version}}"
